name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/web-app . --push

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    # - name: Deploy to Kubernetes
    #   run: |
    #     echo ${{ secrets.KUBECONFIG }} | base64 --decode > kubeconfig.yaml
    #     export KUBECONFIG=kubeconfig.yaml
    #     kubectl apply -f kubernetes/deployment.yaml # Adjust the path and file name
    #   env:
    #     KUBECONFIG: ${{ secrets.KUBECONFIG }} 

    - uses: danielr1996/kubectl-action@1.0.0
      name: Deploy to Kubernetes
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }} 
        args: apply -f kubernetes/deployment.yaml

    - name: Clean up
      run: |
        docker logout
