name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/web-app . --push

    # - uses: danielr1996/kubectl-action@1.0.0
    #   name: Deploy to Kubernetes
    #   with:
    #     kubeconfig: ${{ secrets.KUBECONFIG }} 
    #     args: apply -f kubernetes/deployment.yaml

    - name: Deploy to Kubernetes
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBECONFIG }} 
        version: v1.25.0 
        command: apply -f kubernetes/deployment.yaml

    - name: Clean up
      run: |
        docker logout
